---
- hosts: oob-mgmt-server
  user: cumulus
  become: yes
  become_method: sudo
  roles:
#    - netq-redis
    - netq-cli

#- hosts: leafs
#  user: cumulus
#  become: yes
#  become_method: sudo
#  roles:
#    - netq-agent

#- hosts: spines
#  user: cumulus
#  become: yes
#  become_method: sudo
#  roles:
#    - netq-agent

- hosts: servers
  user: cumulus
  become: yes
  become_method: sudo
  roles:
    - netq-cli 
