# Add the EA repo to the sources list

- name: Add Cumulus apt gpg key
  apt_key: keyserver=p80.pool.sks-keyservers.net id=DFEFCFBC5A1A622FEFCA76497EB364B4A88BBC95
- name: Enable EA deb apt repo
  apt_repository: repo='deb [arch=amd64] http://repo3.cumulusnetworks.com/repo CumulusLinux-3-early-access cumulus' state=present update_cache=no
- name: Enable EA deb-src apt repo
  apt_repository: repo='deb-src [arch=amd64] http://repo3.cumulusnetworks.com/repo CumulusLinux-3-early-access cumulus' state=present update_cache=no
- name: Enable CL deb repo
  apt_repository: repo='deb [arch=amd64] http://repo3.cumulusnetworks.com/repo CumulusLinux-3 cumulus upstream' state=present update_cache=no
- name: Enable CL deb-src apt repo
  apt_repository: repo='deb-src [arch=amd64] http://repo3.cumulusnetworks.com/repo CumulusLinux-3 cumulus upstream' state=present update_cache=no
- name: Enable CL updates deb apt repo
  apt_repository: repo='deb [arch=amd64] http://repo3.cumulusnetworks.com/repo CumulusLinux-3-updates cumulus upstream' state=present update_cache=no
- name: Enable CL updates apt-src repo
  apt_repository: repo='deb-src [arch=amd64] http://repo3.cumulusnetworks.com/repo CumulusLinux-3-updates cumulus upstream' state=present update_cache=no

# Install netq-agent package
- name: Add the netq package
  apt: name=cumulus-netq update_cache=yes allow_unauthenticated=yes

# Ensure ntpd is running
- name: Ensure ntp is running
  service: name=ntp state=started

# Set netq-agent configuration
- name: Set netq-agent configuration
  template: src=netq-cli.yml dest=/etc/netq/netq-agent.conf
