# Add the EA repo to the sources list
- name: Enable EA deb apt repo
  apt_repository: repo='deb http://repo3.cumulusnetworks.com/repo CumulusLinux-3-early-access cumulus' state=present

- name: Enable EA deb-src apt repo
  apt_repository: repo='deb-src http://repo3.cumulusnetworks.com/repo CumulusLinux-3-early-access cumulus' state=present

# Install netq-agent package
#- name: Add the netq-agent package
#  apt: name=cumulus-netq update_cache=yes

# Check if netq-dev is installed
- name: check netq package status
  command: dpkg-query -W python-netq_0.1-cl3eau1_all
  register: netq_dev_check_deb
  failed_when: netq_dev_check_deb.rc > 1
  changed_when: netq_dev_check_deb.rc == 1

# Push the dev build of netq
- name: Copy NetQ dev package
  copy: src=python-netq_0.1-cl3eau1_all.deb dest=/home/cumulus/python-netq_0.1-cl3eau1_all.deb owner=cumulus group=cumulus mode=644
#  when: netq_dev_check_deb.rc ==1

# Install dev build of netq
- name: Install netq dev build
  apt: deb="/home/cumulus/python-netq_0.1-cl3eau1_all.deb"
  sudo: true
#  when: netq_dev_check_deb.rc ==1
  notify: restart netq-agent

# Ensure ntpd is running
- name: Ensure ntp is running
  service: name=ntp state=started

# Set netq-agent configuration
- name: Set netq-agent configuration
  template: src=netq-agent.yml dest=/etc/netq/netq-agent.conf
  notify: restart netq-agent

# Start the netq-agent
- name: Start netq-agent
  service: name=netq-agent state=started
